"""Centralised Qt/graphics imports for reuse across modules."""

from PyQt5.QtWidgets import (
    QApplication,
    QFrame,
    QGraphicsDropShadowEffect,
    QGraphicsOpacityEffect,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMainWindow,
    QMessageBox,
    QProgressBar,
    QPushButton,
    QSizePolicy,
    QShortcut,
    QSpacerItem,
    QStackedLayout,
    QStackedWidget,
    QVBoxLayout,
    QWidget,
)
from PyQt5.QtCore import (
    QEasingCurve,
    QMetaObject,
    QRect,
    QRectF,
    QSize,
    Qt,
    QPropertyAnimation,
    QTimer,
    pyqtSignal,
    pyqtSlot,
)
from PyQt5.QtGui import (
    QBrush,
    QColor,
    QFont,
    QIcon,
    QImage,
    QKeySequence,
    QLinearGradient,
    QPainter,
    QPainterPath,
    QPixmap,
    QScreen,
)
import cv2  # type: ignore
import numpy as np  # type: ignore
import pyaudio  # type: ignore
import qtawesome as qta

__all__ = [
    "QApplication",
    "QFrame",
    "QGraphicsDropShadowEffect",
    "QGraphicsOpacityEffect",
    "QHBoxLayout",
    "QLabel",
    "QLineEdit",
    "QMainWindow",
    "QMessageBox",
    "QProgressBar",
    "QPushButton",
    "QSizePolicy",
    "QShortcut",
    "QSpacerItem",
    "QStackedLayout",
    "QStackedWidget",
    "QVBoxLayout",
    "QWidget",
    "QEasingCurve",
    "QRect",
    "QRectF",
    "Qt",
    "QPropertyAnimation",
    "QTimer",
    "pyqtSignal",
    "pyqtSlot",
    "QSize",
    "QBrush",
    "QColor",
    "QFont",
    "QIcon",
    "QImage",
    "QKeySequence",
    "QLinearGradient",
    "QPainter",
    "QPainterPath",
    "QPixmap",
    "QScreen",
    "cv2",
    "np",
    "pyaudio",
    "qta",
]
